//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamKaminariAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBelt
    {
        public System.Guid Id { get; set; }
        public System.Guid CustomerId { get; set; }
        public byte BeltId { get; set; }
        public Nullable<System.DateTime> DateAchieved { get; set; }
    
        public virtual Belt Belt { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
